### ISSUE TITLE
Two problems on launch. Main storyboard does not exist and missing initial view controller

### ISSUE THREAD

**Issue by andrewclaus** [pingidentity/mobile-authentication-framework-ios#1]
When running this sample project on Xcode 12.0.1, the app crashes upon launch with "unable to find storyboard 'Main'" 

This was solved by updating the Info.plist value from "Main" to "AuthMain" for key "UISceneStoryboardFile".

After this, the app ran but no UI was displayed on screen because the storyboard was missing an initial view controller.
 
This was solved by going into the AuthMain.Storyboard, select the view controller, and check the box for "Is Initial View Controller"

**Comment by andrewclaus** [comment]
Although I am starting to suspect that this "sample project" was not designed to be run on its own. Although the changes above allows the included sample application to run, it does not do anything. It looks like this was designed to be dropped into an existing project of my own.

I would recommend that the sample project adds the minimum amount of work to get the PingAuthentecationUI to be displayed. (Just a blank UIViewController with a button should do?) I will try this myself shortly and report the results here.

**Comment by amitnadirping** [comment]
This code is not stand alone but need to be integrated in your project, following the readMe instructions. In order to see example of usage, please review the sample app example source code for iOS [here](https://github.com/pingidentity/pingone-mobile-sdk-ios). There you can see the authnAPI code folder integrated in the project.
